version: "3.8"

services:
  localstack:
    container_name: localstack_service
    image: localstack/localstack:0.14.5
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ../tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
